### PR TITLE
Add update-time note

### PR DESCRIPTION
**Pull request by thisIsTheFoxe**
_So, I just checked, and for me it just turned April 6 and I though: "when will the data from yesterday be available?" So, I checked CSSEGISandData/COVID-19 and was happy, but then I thought what if someone else has the same question...._

Anyway, I added a small note (to the footnote) to **roughly** indicate when new data should be available, based on the CSSEGISandData/COVID-19 & nytimes/covid-19-data repos and their commits..

### CODE REVIEW

**Comment by waldyrious** [comment]
The "12pm EST" should probably use the same format as "00:00 UTC". Also, as a global project, it would be nice to include the UTC equivalent of the EST time as well.

**Comment by thisIsTheFoxe** [comment]
something like this? ^^

**Comment by aatishb** [comment]
@all-contributors add @thisIsTheFoxe for content

**Comment by aatishb** [comment]
@all-contributors add @waldyrious for review

**Comment by aatishb** [comment]
Thanks @thisIsTheFoxe @waldyrious!

**Pull request closed without merging**
