### PR TITLE
View states/provinces of China, Australia, Canada and US

### LINKED ISSUE #5: Add breakdown by state (USA, Canada, etc)
each states should have different curves

### PR DESCRIPTION
**Pull request by exclipy**
This is a work-in-progress proposal to add the ability to show the provinces of China, Australia and Canada (these are the three contiguous countries which are broken down in the underlying data).

Sorry it includes a bit of a refactor and I had to change the behavior of the country/region selector quite a bit.  Instead of using the predefined list of default-selected countries, it now selects the top 15 by default, plus Singapore, Japan and Qatar (because they have interesting charts).  I also took the liberty to sort the country list in descending order of number of cases.  The code is still a bit messy (eg. it still refers to states as countries).

Just sending this out as a request for comment - let me know if this direction is useful.  I can take things out of this PR to make it more minimal if you want.

Demo: https://exclipy.github.io/covidtrends/

Partially resolves #5  (but the US is not covered because it's not in this data set)

### CODE REVIEW

**Comment by exclipy** [comment]
I've added the states of the US now (I stole byteit101's code from #6)

**Comment by aatishb** [comment]
Hi! Thanks so much for working on this! This is super interesting and looks really helpful. I like the idea of a new Region selector. I also like the organization of exclusions, renames, and notable countries.

Some other comments / questions:

1. I'm not sold on sorting countries by cases as yet. My concern is some may not understand this and struggle to locate their country as a result. I think for now, I would prefer to stick with alphabetic (but perhaps hold on to the maxCases in code, in cases we want to add a re-sort option later?)

2. Another small thing: it would be nice if when there is no data (e.g. deaths for Australia/Canada), the graph is emptied but does not disappear, similar to when you deselect all the data in the current view.

3. So if I understand this correctly, it looks like for the US states you are using @byteit101's code from #6 which is sourced from NYT, and for the remaining regions, you are using JHU data. Did I get that right?

4. One thing we should be careful of is that the JHU data format tends to change unexpectedly. I can look into this a bit more as I've been working closely with their data. Related: are there are other regions for which they have more fine grained data as well?

5. @byteit101, Are you ok with your code being included into this PR? (I'll make sure to add a contributors section so that everyone is credited.) 

Thanks all for your work on improving this!

**Comment by exclipy** [comment]
> I'm not sold on sorting countries by cases as yet. My concern is some may not understand this and struggle to locate their country as a result. I think for now, I would prefer to stick with alphabetic (but perhaps hold on to the maxCases in code, in cases we want to add a re-sort option later?)

OK, I'll stick to alphabetic.

I'm also not sure about auto-selecting the top 15 cases because it's interesting to look at the countries/states across the spectrum of progression.  How did you select the default-selected countries and how do you think I should select the default-selected countries/states/provinces?

> Another small thing: it would be nice if when there is no data (e.g. deaths for Australia/Canada), the graph is emptied but does not disappear, similar to when you deselect all the data in the current view.

OK.

> So if I understand this correctly, it looks like for the US states you are using @byteit101's code from #6 which is sourced from NYT, and for the remaining regions, you are using JHU data. Did I get that right?

Yes.

> Related: are there are other regions for which they have more fine grained data as well?

I saw they had for example France, UK, Netherlands and Denmark but those were basically split into their outlying territories like New Caledonia, Cayman Islands, Sint Maarten, Faroe Islands, etc.

I'll be back soon with an update to fix the above.

**Comment by exclipy** [comment]
> One thing we should be careful of is that the JHU data format tends to change unexpectedly.

On this note, I was thinking of breaking out a DataPreprocessor interface to normalize among different data sources (we now have JHU and NYT but we might want to add more such as from Kaggle and ECDC - see [full list](https://docs.google.com/spreadsheets/d/1lyPuMoolIvbJQjZkETHA-y1fCXRIBZbCstr_NH9Q5TQ/edit#gid=0)).

I'll be happy to do a bunch more refactoring of this code (eg. breaking into multiple files) too but this will be a bit disruptive to open PRs, so let me know if I should proceed.

**Comment by aatishb** [comment]
Thanks for this. I will take a look. Let's hold off on any major refactoring for now. I want to be cautious about moving too fast on including more data sources and for now would err towards relying on JHU as much as possible. We can reevaluate further down.

**Comment by byteit101** [comment]
> @byteit101, Are you ok with your code being included into this PR? (I'll make sure to add a contributors section so that everyone is credited.)

Of course! I don't see a license file existing, so my contributions are licensed under Apache 2

> How did you select the default-selected countries and how do you think I should select the default-selected countries/states/provinces?

FWIW, I selected the defaults for my view via the unscientific manual removal of enough states to avoid text overlapping the other day. Not scalable at all though :-)

>  I was thinking of breaking out a DataPreprocessor interface to normalize among different data sources (we now have JHU and NYT...

I tried to be minimally invasive with my PR by just normalizing the NYT long format to the JHU wide format.

**Comment by exclipy** [comment]
> I'll also need to update the code for the 'custom link button' to include regions

Actually I already updated that button in [9addff](https://github.com/aatishb/covidtrends/pull/13/commits/9addff138e9a3e2634c694351cbda6e7cc6d128e)

**Comment by saufrecht** [comment]
I added a [pull request](https://github.com/saufrecht/covidtrends/pull/2) specifically for the license.  Because the JHU data is not actually in this repository, I don't think there's a licence issue.  The attribution and links that are user-visible should cover that.

When this thread and pull request are caught up, I'd be curious to hear your thoughts on making it easy to use this format with data from other sources that don't overlap with JHU.  I.e., I hacked it together with Bay Area data compiled by [SFist](https://sfist.com/bay-area-coronavirus-information-updated-daily/), to show county-level data.  All of these numbers are presumably included in the JHU counts, but that approach doesn't give any way to see the low-level trends.

**Comment by aatishb** [comment]
Hi @exclipy. I'm just reviewing these changes. I think I may have found a possible bug. Here are the steps to reproduce it:

1. Set slider to last date on default world view (Currently 3/29)
2. Switch region to US (notice that date has changed to 3/28, which is unexpected)
3. Switch region to China

When I do this, I no longer see the markers for the China provinces, and the play behavior is broken.

I'm thinking that ideally, the behavior for changing regions should be the same as the current behavior for changing from confirmed cases to reported deaths, where the date slider jumps to the most recent date, irrespective of the current date.

I was thinking one way to do this would be to add something like `this.day = this.dates.length` after setting `this.dates`, but this breaks the rescaling behavior when switching between regions. I'll look into this some more, but just sharing where I'm at in cases you see a fix.

**Comment by aatishb** [comment]
Ah, I think I see a solution. We probably need to bind the selectedRegion to the graph component, and add some code similar to https://github.com/aatishb/covidtrends/blob/master/vue-definitions.js#L237-L240 but for selectedRegion instead of selectedData. Trying this...

**Comment by aatishb** [comment]
ok, I made the above change. It works nicely when switching between JHU regions, but there still seems to be an off by one error when switching to the NYT region. cc @exclipy

**Comment by exclipy** [comment]
Thanks for finding and fixing this bug!  What's the off-by-one-error?

**Comment by aatishb** [comment]
Hmm.. strange. It's what I described in [this comment](https://github.com/aatishb/covidtrends/pull/13#issuecomment-606280009) but I can't reproduce it at the moment. It seemed to be a problem on my end when the JHU and NYT data were both updated till 3/29. I'll check this again tomorrow to see if this issue recurs when the NYT data updates to 3/30.

In the meanwhile, I'm running into another potential issue. Maybe this is just a problem on my end, but when I reload using the shareable link, it loads the default 'countries' rather than the ones I selected. Could you please check and let me know if this is a problem on your end as well?

Finally, I'm thinking it would be nice if in the create shareable link we could replace 'country' with something like 'location' as this makes sense for regions other than 'World' (otherwise we end up with URLs like /?region=US&country=New+York ). We should be careful not to break the existing URLs that use 'country' e.g. /?country=Afghanistan

**Comment by rachellevanger** [comment]
US numbers are tracked down at the county level on JHU. Thoughts on adding this breakdown in addition to state level for the US?

**Comment by exclipy** [comment]
> when I reload using the shareable link, it loads the default 'countries' rather than the ones I selected. Could you please check and let me know if this is a problem on your end as well?

Fixed

**Comment by aatishb** [comment]
Thank you. 

Following up on the off by one bug, as suspected, it seems to have come back now that the NYT data for 3/30 is in. To recreate: switch region slider from to US and then to any other region. All the country markers disappear and the play button stops working. If you drag the date slider it fixes this. The bug only occurs when switching between JHU & NYT data, not between different regions in JHU. I suspect is has something to do with how the date is parsed / stored when we jump between datasets. Will save a local version of the current datasets so I can test this further.

**Comment by aatishb** [comment]
I'm understanding the issue a bit more. 

When we switch regions, the graph updates the date to the length of the this.dates array (using selectedRegion watcher). However the this.dates array sometimes has lengths that are off by 1 between the JHU & NYT data, which causes the bug. 

This would have been a bug before I added the selectedRegion watcher as well, following [these steps](https://github.com/aatishb/covidtrends/pull/13#issuecomment-606280009) to reproduce, it's just more evident now.

**Comment by LannyRipple** [comment]
Super excited to see this commit happen.  My wife is an infectious disease physician and most of her work up to now has been calming staff.  (Changed in the last few days as the ventilator beds fill up.). Having a view by US states and the Minute Physics video to explain what people are seeing would give her a great tool for educating and (hopefully) settling people down when the curves do start falling off.

**Comment by aatishb** [comment]
@exclipy: is the didRegionChange variable added for efficiency or was it needed for some specific behavior? Not seeing a change in behavior if I leave it out.

**Comment by aatishb** [comment]
Am hoping to merge this within a day. It's very close, will spend some time today testing.

**Comment by exclipy** [comment]
> @exclipy: is the didRegionChange variable added for efficiency or was it needed for some specific behavior? Not seeing a change in behavior if I leave it out.

It's so that if you change the region, it will overwrite the list of "countries" whereas if you change the cases/deaths selector, it does not change it.

**Comment by aatishb** [comment]
Thanks @exclipy and @byteit101 for all your hard work on this!

**Comment by byteit101** [comment]
Nice! Though it looks like because my code was copied vs merged I'm not on the contributors list?

**Comment by aatishb** [comment]
@byteit101 sorry about this! I'm new to managing repositories and didn't realize there was a better way to go about this.

We are using the all contributors bot to acknowledge contributions, which are displayed on the readme. So let me go ahead and add you both there (fingers crossed that this works):

@all-contributors please add @byteit101 and @exclipy for code.

**Comment by aatishb** [comment]
@all-contributors please add @byteit101 for code

**Comment by aatishb** [comment]
@all-contributors please add @exclipy for code.

**Comment by byteit101** [comment]
Oh nifty, I've not used the allcontributors bot either, and didn't realize it worked like that. Thanks!

**Comment by R7E** [comment]
Is it possible to include in the right column an all option? It would be great to be able to compare Hubei with Italy and New York.

**Comment by exclipy** [comment]
I would like that too! File a new issue for that?

I tried doing it but I think it needs a bit of a refactor. Currently, the d3.csv function is used to load data and it can only read from one CSV. But to compare New York with Hubei, we'd have to pull both CSVs and merge them.

I just got really busy with other things though so I can't work on it.

**Comment by R7E** [comment]
Created a new issue for this https://github.com/aatishb/covidtrends/issues/42.

**Pull request merged**
