### PR TITLE
Auto update url

### PR DESCRIPTION
**Pull request by aatishb**
Merges #179

### CODE REVIEW

**Comment by aatishb** [comment]
Hi @MrSpiffyClean. Great work on this, the changes look great. 

I made a new branch as I wanted to try out some reorganization and didn't want to get in the way of your branch.

I took a stab at cleaning up the logic in the createURL function a bit. Using flag variables and break statements can become difficult to maintain down the road as it becomes complicated for other coders to parse the logic. So instead, I tried to replace these with array comparison checks. 

I wonder if you could test this and let me know if it introduces any bugs compared to your code, and if it still has the expected behavior. Thanks! (cc @rpkoller)

**Comment by rpkoller** [comment]
performance wise it got worse :/ 

that is the lighthousetest of pull request by @MrSpiffyClean 

Bildschirmfoto 2020-05-12 um 16 26 56

that is the lighthouse test by your branch @aatishb (before your pushed the commit with the double update

Bildschirmfoto 2020-05-12 um 16 27 11

**Comment by rpkoller** [comment]
as i stated in one other issue yesterday the toll for the script evaluation time as well as the execution time is quite steep js wise :/

**Comment by aatishb** [comment]
Hmm.. I think the performance metric is somewhat variable and we should ignore small changes to it. e.g. the most recent audit (just pushed a commit) shows a score of 36. There shouldn't be any change in load performance as all the changes only take place on UI input.

**Comment by rpkoller** [comment]
yep you shouldnt act on a single test. and the latest is ok... got just cautious after the changes and the rework in the new branch that the metrics got worth. but your commit afterwards seemed to fix and mitigated it. :) a more in depth performance review might be reasonable when doing the work on the responsive part. but for now it is fine.

**Comment by aatishb** [comment]
Apologies, I accidentally introduced a few bugs. I think I've fixed these now, and this branch should now recreate the behavior of @MrSpiffyClean's branch. (fingers crossed) The main addition here is to remove flag variables & break statements in favor of array comparisons, as these are a bit easier to maintain (more declarative vs imperative code). Mainly a stylistic difference, hopefully it didn't break anything!

I'll wait for @MrSpiffyClean to test before merging.

**Comment by rpkoller** [comment]
i guess it was present before but in case you deselect all but have show doubling time on the label for doubling time is still shown. i would hide the label for the doubling time in case state/territory or country is deselected all.

Bildschirmfoto 2020-05-12 um 18 59 04

aside that i dont find any nitpick. but @MrSpiffyClean had a few cases i particularly looked for. so it is up to him.

**Comment by MrSpiffyClean** [comment]
I had a bit of time to check the code and its behaviour. The code looks cleaner than what I left it, and there was an event caller I left behind that you caught (mostly because I was wondering why label wasn't on the original code and if it was worth it to do something), so thanks for that.

@rpkoller Changing that behavior (with the trendbar) falls a bit outside of the original scope of changing the URL address, so I didn't think to do it now (even if it looks a bit nonsensical).

The response isn't exactly the same as what I did, on an edge case. Giving an example: Select Canada, Select Reported Deaths, and remove the 4 locations one by one (instead of pressing Deselect All):

- Previous code: `?data=deaths&region=Canada&select=none`
- Recent code: `?data=deaths&region=Canada&location=Manitoba&location=New+Brunswick&location=Newfoundland+and+Labrador&location=Nova+Scotia&location=Saskatchewan`

The main difference is that, on reload, the recent code allows for one to go back to Reported Cases and find the previously selected countries. I'm not bothered by this change however, as it might be of use to someone (and as more data is fed, more locations are added, so it's future-proofing of sorts).

There is also something I forgot to account for (mostly because I only thought of looking for it yesterday) which is that default selections (i.e. the URL not having any countries) aren't 100% consistent. In more detail, this can be checked by selecting US, then Reported Deaths, then reloading the page. Louisiana, Connecticut (which wasn't selected before and are replacing Florida and Texas), are now displayed.
Fixing this involves messing around with the way data is loaded, which is something I wasn't exactly willing to do initially.

These are my findings for the time being, everything else sems to work well. The performance issues @rpkoller commented about could be looked into in another issue, eventually.

**Comment by aatishb** [comment]
Wow @MrSpiffyClean, thank you for taking such a close look. This is exactly the kind of thing I was hoping to catch. I would consider this a bug or at least unintended behavior. 

It seems many of the edge cases have to do with the situation where the selectedCountries array is larger than the countries array, which can occur when switching from Confirmed Cases to Deaths.

I pushed a fix for this first issue, looking in to the second issue (changing countries on reload).

**Comment by aatishb** [comment]
The reason for the second issues goes back to an earlier design decision. We had chosen to not update the list of selected countries when switching from confirmed cases to deaths. This is implemented with an updateSelectedCountries variable that can be true or false.

[These](https://github.com/aatishb/covidtrends/blob/master/vue-definitions.js#L245-L257) are the relevant lines.

Otherwise this would overwrite people's selections.

**Comment by aatishb** [comment]
@all-contributors add @MrSpiffyClean for code

**Comment by aatishb** [comment]
Thanks @MrSpiffyClean and @rpkoller for all your efforts on this!

**Pull request merged**
