### PR TITLE
Format date using toISOString

### PR DESCRIPTION
**Pull request by edg2s**
This will use the standard YYYY-MM-DD ISO 8601 date format
instead of giving M/D/Y (the US-only format) to everyone.

### CODE REVIEW

**Comment by edg2s** [comment]
Alternative patch: #22

**Comment by aatishb** [comment]
I appreciate the need to step away from the US-centric format. I'm wondering if displaying dates like 'March 4' would be more widely understandable to all? Thoughts?

**Comment by edg2s** [comment]
That may be harder for people with limited English. If you were going to go do the route of full i18n/l10n, then perhaps localised dates would be better, but in the current setup I think ISO dates will be the most understandable to the most number of people.

**Comment by aatishb** [comment]
Thanks @edg2s. I tried merging this with the current codebase (with the new region selector) to test. Ran into a bug when I switch region from World to US and back to World: `TypeError: "date is undefined"`

Wonder if you have any thoughts on how to fix?

**Comment by edg2s** [comment]
I've rebased locally and can't reproduce that issue (tested Chrome+FF). Are you sure it wasn't just a browser caching issue?

**Comment by aatishb** [comment]
Thanks @edg2s, you're right!

**Pull request merged**
