### PR TITLE
Use number input for doublingTime line

### PR DESCRIPTION
**Pull request by edg2s**
Number input has convenient up/down buttons, and doesn't
limit users to an arbitrary range (<50).

### CODE REVIEW

**Comment by aatishb** [comment]
This makes sense. It also allows for non-integer doubling times. However right now if we type in -1 it messes up the trend line. Maybe we should add a check so that we only accept input >= 1?

**Comment by rpkoller** [comment]
i would even extend it to integer input >= 1  maybe and i would also add an `aria-label` attribute to the field if possible.

**Comment by aatishb** [comment]
+1 to aria-label. I actually kind of like the ability to add decimal input. Most users won't consider it because they'll press the up/down button. However for advanced users, it may be helpful to tell if a country is following a 4.5 day doubling time or whatever. Just a thought, I don't feel very strongly about this.

**Comment by rpkoller** [comment]
you are right @aatishb thats definitely true. haven't seen it from that perspective

**Comment by edg2s** [comment]
Anything >0 should be strictly valid

**Comment by edg2s** [comment]
Given there are no aria-labels on the page currently I assume that would be address in a separate a11y commit.

**Comment by rpkoller** [comment]
aria-labels as well as regular labels are introduced in that pull request in the accessibility branch: https://github.com/aatishb/covidtrends/pull/136

**Comment by edg2s** [comment]
Ok, when that is merged I'll rebase.

**Comment by aatishb** [comment]
> Anything >0 should be strictly valid

@edg2s agreed, will be great if you can add in a check for this.

**Comment by edg2s** [comment]
Testing it for some reason values <1 don't appear to work correctly. They generate the same line as t=1.

**Comment by aatishb** [comment]
On thinking about this some more, I think this is the correct behavior. For our particular graph, the formula for the reference line is 

```
    referenceLine(x) {
      return x * (1 - Math.pow(2, -this.lookbackTime / this.doublingTime));
    }
```
In the limit as doublingTime -> 0, the line approaches y = x. When doublingTime = 1, the reference line is y ~ 0.992 x. 

So there is not much visible difference. (If you look closely, you can see a small shift between doubling time = 1 & 0.1 on a linear scale, but on the log scale this is basically invisible.)

That being said, I think this might be confusing as it's somewhat counter-intuitive, and as far as I know there are no locations with doubling time < 1, so I'm ok with limiting to >= 1.

**Comment by rpkoller** [comment]
> Ok, when that is merged I'll rebase.

@aatishb merged the changes into `master` few minutes ago so you could rebase it now :)

**Pull request merged**
