### PR TITLE
Hide graph when no data is selected

### PR DESCRIPTION
**Pull request by MrSpiffyClean**
Proposed solution for #145.

Essentially just hides the graph and displays the message "Please select some countries to display." if there exists available data but no visible country is displayed. If there is no data available at all (e.g. Australia, deaths) the original message remains.

As always, feedback and review are welcome.

### CODE REVIEW

**Comment by rpkoller** [comment]
nice... one slight detail:  select region -> choose one of the countries (e.g. US) -> deselect all

the headline for the region US is states/territories but the label showing up after deselect all still says "Please select some countries to display."

aside that hiding the whole graph instead of simply hiding the doubling time line and label looks unusual but maybe the better and cleaner choice... more explicit that way

**Comment by MrSpiffyClean** [comment]
Laziness on my part, mostly. I could either change the text to be more neutral (i.e. instead of countries, say locations) or add more checks. I would go for the first option, as that doesn't overload the index.html file and it wouldn't need to be looked after should other regions with different names for states (like prefectures and districts or cantons).

Not showing the line at all and just having an empty graph, showing nothing more than gridlines, seems to me the option that looks worse, and it also doesn't say anything else about what an user is supposed to do.

I remembered checking the issue tracker, and this also seems to solve #147.

**Comment by rpkoller** [comment]
haha i was still thinking about a suggestion for a neutral sentence working for both the countries as well as the states/territories while you already committed the new patch adding an automatic switch for the text ;) cool! works and i like it. 

and yep as i said it just looked unfamiliar at first seeing the grid getting removed. but it is the better choice and decision! :)

**Comment by MrSpiffyClean** [comment]
Noticed that the page already displays the correct name for the locations on the list, so it was a matter of using that name in the message. Unsure on how to deal with capitalization in the middle of a sentence though.
Lighthouse seemed to timeout

**Comment by rpkoller** [comment]
hmmm how about to apply the `toLowerCase` method to `regionType` to get a lower case output?

**Comment by rpkoller** [comment]
hmmm pity. only `approval` worked within the commit. hoped for some thumbs up emoji there as well ;) but looks good that way :)

**Comment by aatishb** [comment]
Thanks @MrSpiffyClean for this, and @rpkoller for reviewing! Will plan to merge this tomorrow.

The changes look good, very neat & minimal solution.

The only thing I'm wondering is whether we still require the checks involving covidData.length now that we have this new check. I'm assuming that we do, but want to go back and check. 

(From what I recall, the covidData.length check was created to ensure the graph doesn't display until the data first loads, and also that the graph is hidden when there is not data for the parameters, e.g. Deaths in Australia.)

**Pull request merged**
