### PR TITLE
Add Curve for Worldwide Stats

### PR DESCRIPTION
**Pull request by bchurchill**
This is in response to #86.  A few folks have been requesting to see a curve with worldwide totals, and I was interested in this too!  This adds "World" to the list of countries; selecting it shows the worldwide totals.  I spent some time testing and verified that it works for both 'conformed cases' and 'reported deaths'.  Also took care to exclude the worldwide figure from the top 10 countries (which are automatically selected) so that the animation looks clean when you come to the page for the first time.

This is literally a "Hello World" pull request :D

### CODE REVIEW

**Comment by bchurchill** [comment]
@all-contributors add @bchurchill  for code

**Comment by rpkoller** [comment]
hm ux wise as well as semantical/categorization wise  i consider it odd if you have `world` as selected region that the checkbox for the actual `world` curve is then hidden at the end of the list of countries worldwide due to the alphabetical sort. Either set the `world` curve also as default like US, Russia, Brazil etc shown on initial page load or lets rethink and recategorize the select region select box and also add curves for the seven continents alongside the world curve?

**Comment by bchurchill** [comment]
Yeah I totally get what you're saying!  I was thinking about that too.  The option that appeals most to me is to have an option to show each of the continents along with the world as apart from the countries.  Is that something you think the project would like?  I saw a lot of people asking for Europe data on the tracker, so I think it makes sense.

**Comment by bchurchill** [comment]
Something like this:

https://imgur.com/1TJ5eDB

I'm wondering if cleanup of the 'customization' section would be needed to make more space.  Or perhaps the 'Geographies' section should come after the list of countries?

**Comment by bchurchill** [comment]
Oh, the reason I didn't make 'World' appear by default is because if you watch the animation then the 'World' dot is exactly where the 'China' dot is, and it makes the text overlap.  I felt that wasn't ideal.  I guess one possibility is to try to move the world label in another place, but that feels like a hack.

**Comment by bchurchill** [comment]
I'm open to suggestions on how to proceed!

**Comment by rpkoller** [comment]
> Something like this:
> 
> https://imgur.com/1TJ5eDB
> 
> I'm wondering if cleanup of the 'customization' section would be needed to make more space. Or perhaps the 'Geographies' section should come after the list of countries?

you wanted to show the geographies and country subcategories only if the world region is selected?

**Comment by bchurchill** [comment]
@rpkoller  Yes, my current thought is if 'World' is selected from the region selection dropdown, I propose making the list of continents ("geographies"), along with an option to display a line for the world, visible BELOW the list of countries.  Here's a mockup:

https://imgur.com/a/WZJ0dQV

I'm thinking to put the geographies below the list of countries so that it doesn't disrupt the current UI at all, but we can move it to a more prominent place later IF folks want to do so.  If this is agreeable, I can take a stab at this on the weekend.

**Comment by aatishb** [comment]
Hi @bchurchill, maybe hold off on this for now.  I'm intrigued by the idea of providing a higher level geographical organization, but I think we should think more on what exactly to implement.

One option could be that selecting Asia under geographies selects all Asian countries. Another option is that it creates a new curve with the total numbers for Asia. I'm not sure which is better suited for us. Also whenever we get into adding geographical regions, there are some subtleties with regards to which countries belong in which region i.e. geopolitical equivalent of edge cases (I think @waldyrious was maybe discussing this on a thread?) so we may need to tread carefully.

So overall I feel this is a significant change that we should discuss more on an issue, to come to an agreement on whether it makes sense for this branch and if so how best to go about it.

**Comment by aatishb** [comment]
That all said I like your addition and even shared it via email to someone who wrote in requesting exactly this (who was excited to see it). So clearly it's interesting and useful to people, I just want to think through whether it's right for this branch. 

A separate thought is that it would be nice if we could more prominently share 'mods' of Covid Trends, perhaps by creating a markdown page for this that we link to.

**Comment by waldyrious** [comment]
> whenever we get into adding geographical regions, there are some subtleties with regards to which countries belong in which region i.e. geopolitical equivalent of edge cases (I think @waldyrious was maybe discussing this on a thread?) so we may need to tread carefully.

I believe you're referring to [this](https://github.com/aatishb/covidtrends/issues/66#issuecomment-623177950) — indeed it's not clear-cut, but we can always defer to third-party and/or reasonably broad definitions, as I suggested there. Wikipedia's [Boundaries between the continents of Earth](https://en.wikipedia.org/wiki/Boundaries_between_the_continents_of_Earth) should provide ample material for making an informed decision.

**Comment by aatishb** [comment]
Thanks @waldyrious , that's the thread I was thinking of. I agree using some standard / widely accepted existing categorization makes sense. Welcome thinking through this further on an issue.

**Comment by bchurchill** [comment]
Hi all,

I'm closing this pull request for now but wanted to share that I've implemented the selection of continents in the fork, with the UI change suggested earlier:

https://bchurchill.github.io/covidtrends/

Now it's possible to select continents and plot those as well.  I thought it would mention it since a few people showed interest @waldyrious @thisIsTheFoxe 

In terms of dividing countries into continents, I used the CIA world factbook since they had a clear list of countries for each continent (although some countries get double-counted).

@aatishb  if you're interested in merging this in at some point, just drop me a line.  It probably needs some more work before it's ready.

**Comment by rpkoller** [comment]
@bchurchill i've checked the latest revision. i have to admit i've never been a fan of comparisons in between countries or even less on a continental level due to the fact that the sampling efforts and protocols differ vastly in between countries which makes comparisons not very meaningful imho... but never the less getting an idea about the overall growth trend for the different continents is quite surprising. would have expected different curves especially for europe. but never the less i get the basic purpose behind it now and start liking the idea ;)  

a few comments again about the current revision. 

- each continent might need an info button showing which countries are counted into each continent. in the current state you have no idea which country is accounted to which continent. (a small info button showing a widget on hover or click with the list of accounted countries might be helpful) 

- "select region":  i would rename it into e.g. "select scope" and list the following three categories : 1) Continents 2) Countries 3) Regions & Provinces. 

- Continents: show the current list with "world" on top of the list

- Countries: keep things like they are currently on https://aatishb.com/covidtrends/ .... 
in your current version you had grouped continents and countries into one view. that brought in the issue with "deselect all" and "select all". me as a user thought that "deselect all" is the scope for countries it is wrapped into so the "deselect all" is applied only to the countries underneath. currently in your revision with "deselect all" you clear all continents above as well as the countries underneath the button. something i wouldnt expect as a user. leading up to more clicks to mitigate the deselection action turning then into frustration ;) on a side note i suppose you merged countries and continents into one view to make it possible to mix the display of countries and continents? wouldnt that be compare apples with pears based on my initial points in regards of differing sampling efforts and protocols. it is already debateable to compare countries with each other but to compare countries with whole continents i dont know.  

- Regions & provinces: like in your current version replace the continents section with the list of countries having region & province data available. make a condition that only one country could be selected and based on the selection in the list underneath show the according provinces or regions of the selected country? 

those would be my initial thoughts and nitpicks about your current version. but i like the idea and general direction. @aatishb would just have to chime in and start with his suggestion of "Welcome thinking through this further on an issue." ;)

**Pull request closed without merging**
