### PR TITLE
Fixes #103: Add plotly-basic.min.js & move script tags to the bottom of index.html

### LINKED ISSUE #103: Use plotly-basic.min.js instead of plotly.min.js
Since the Plotly Javascript asset is huge with 3,3mb in an already minified version I've taken a look at the Plotly Github page and checked if there is the chance to use only a subset of its framework. And indeed it is. Downloaded the archive and tested to load the covidtrends page locally by replacing the plotly.min.js (3,3mb) with plotly-basic.min.js (886kb) and everything is still working properly. Alongside i would also move the two script calls in the head down to the end of the index.html file. CSS is render blocking while JS is parse blocking so keeping the JS files up there especially such huge ones is not that good of an idea. ;) Could create a pull request.

### PR DESCRIPTION
**Pull request by rpkoller**
- I've downloaded the most recent release of Plotly (1.52.3 -> 1.53.0)
- Used `plotly-basic.min.js` instead of `plotly.min.js`. (883kb vs 3,3mb)
- Moved the two JS tags down to the bottom of `index.html` and placed them right in front of `vue-definitions.js` so the loading of the two bandwidth intensive JS assets isn't parse blocking the html in the rest of the head and body. 
- Left the `plotly.min.js` in for the moment could be removed later on. 
- Tested the graph generation locally and everything kept working flawlessly (MacOS 10.13.6 with latest Safari, Firefox and Chrome)

Fixes issue #103

### CODE REVIEW

**Comment by aatishb** [comment]
Hi @rpkoller, thanks for this! Good to know about plotly-basic. Just tested and it I agree it seems to work great.

My only concern is with the script tags at the bottom of the page, I get a visible flash of the raw html before vue is loaded, which doesn't seem ideal. So perhaps the current order with script tag on top has a helpful side effect of preventing this?

Let me know if you see the same, and what you think.

Screen Shot 2020-04-19 at 6 51 52 PM

**Comment by rpkoller** [comment]
oh i haven't noticed that since i was testing only locally. retried now with simulating a 3g connection in chrome devtools and i am able to reproduce your shown issue. i agree that isn't a decent experience, sorry for that... 
did a brief research ( i am not really used to vue.js) and noticed there is a way to hide `{{vue tags}}` in case the app is not loaded yet. is accomplished with v-cloak. the only thing i am uncertain now is how to reroll a pull request ;)))) that is something i've never done. the issue you described i've already fixed locally here.

**Comment by aatishb** [comment]
Thanks for looking into it! I believe you can just commit your changes and push to the same branch / fork in which you made the pull request, they should just automatically show up here. I'm happy to make the fix as well.

**Comment by aatishb** [comment]
I'd say for now maybe let's just move the tags back to the top & separate this from vue cloak idea to focus this PR. Thanks for mentioning the 3g connection simulation  in Chrome -- that's great to know about!

**Comment by rpkoller** [comment]
so shall i simply make another commit moving script tags up again and the other vue cloak in another pull request in the next days?

**Comment by aatishb** [comment]
👍That sounds good to me. The vue cloak is less of an immediate priority.

**Comment by rpkoller** [comment]
Oh indeed it got added without any further ado on my side. just pushed the change to my forked repo and it got added automatically in here. 

and about the vue cloak. well performance wise it makes a difference if you load everything in the head or the css in the head and the js at the end of the body nevertheless. but for now you are right. no immediate priority. the plotly-basic is worth enough already ;)

**Comment by aatishb** [comment]
Thanks @rpkoller!

**Pull request merged**
