### PR TITLE
Pull out HK & MO to country level view

### PR DESCRIPTION
**Pull request by aatishb**
This is a draft solution to #2. Needs a bit of testing, particularly for the URL load features. Builds on code by @neon-ninja & @exclipy.

### CODE REVIEW

**Comment by aatishb** [comment]
- [ ] Check for double-counting, i.e. if HK & MO numbers are also being counted in Mainland China.
- [ ] Check URL load

**Comment by sjmackenzie** [comment]
Love it, thank you @aatishb!

**Comment by lionello** [comment]
I made #51 for the same reason, but as a different (less politically sensitive) solution.

**Comment by sjmackenzie** [comment]
Looking forward to a merge!

**Comment by aatishb** [comment]
Did a spot-check, looks like the numbers add up correctly (Macau doesn't show up in the graph  as yet because <50 cases). Looks good to go.

Screen Shot 2020-04-04 at 10 45 29 AM

**Comment by aatishb** [comment]
@all-contributors add @neon-ninja for code

**Comment by sjmackenzie** [comment]
One massive sloppy kiss, I appreciate this.

**Pull request merged**
