### PR TITLE
Internationalize date

### PR DESCRIPTION
**Pull request by aatishb**
#28

### CODE REVIEW

**Comment by aatishb** [comment]
Hi @edg2s can you test with the current data and see if you run into the issue? I'm seeing it as of now, and think this is related to an earlier issue to do with date array length changing between NYT and JHU data. I'm thinking of rolling back this change for now until we can resolve this.

**Comment by aatishb** [comment]
Went ahead and rolled this back. Will look into the bug. https://github.com/aatishb/covidtrends/commit/f4b966d0eb920c346b718e52b040d419ecf0d0b6

This issue as I see it is when NYT & JHU have the same latest date, switching from JHU -> NYT -> JHU breaks the graph. Let me know if you aren't able to reproduce it.

**Comment by edg2s** [comment]
> Hi @edg2s can you test with the current data and see if you run into the issue?

What is the issue? I can't see it described anywhere...

**Comment by aatishb** [comment]
When NYT & JHU have the same latest date, switching from JHU -> NYT -> JHU breaks the graph by raising the error in the console log: `TypeError: "date is undefined"`

When NYT & JHU have different last dates, this is not an issue.

**Pull request merged**
