### PR TITLE
Auto-update country URL

### PR DESCRIPTION
**Pull request by MrSpiffyClean**
Proposed solution for #163.

The submitted code does some things:
- Removes the Create Shareable Link button.
- Automatically updates the URL address whenever a country/location button is pressed, whenever the parameter/region/scale is changed and whenever the trending line is changed (disabled or value changed)
- Whenever the page displays default values, the address bar doesn't clog up with all the countries and omits them until someone presses more countries.
- Whenever someone selects all or none countries, the same logic above applies, and a new parameter, `select`, is used.

I've tested the code locally (using the simple Python server) and everything seems to work properly, although any sort of code review is very welcome (as I'm still a bit new to JS).

~~There is an odd case whenever someone selects all countries and then changes to Reported Deaths, instead of showing the simplified parameter, the URL bar does clog up a little. The end result is the same.~~(Fixed)

Feedback is welcome.

### CODE REVIEW

**Comment by rpkoller** [comment]
out of curiosity is it necessary that the question mark on the initial page load (with the default values) is shown? that url looks a bit odd ;) https://deploy-preview-179--frosty-benz-8c81bf.netlify.app/?  aside function wise it looks fine and works as expected (at least from my perspective but i am not js savvy ;))) )

**Comment by MrSpiffyClean** [comment]
You are right, it does look a bit odd. I might have seen it while testing but was never bothered by it. Anyway, I've managed to track down the fault and do a quick fix, it should work as expected now.

**Comment by rpkoller** [comment]
yep I can confirm, the `?` is gone for the default view now :) cool

**Comment by aatishb** [comment]
Wow, @MrSpiffyClean this is a big one! Thanks for submitting this, I'll aim to review by Tuesday.  @rpkoller thanks for testing!

**Comment by MrSpiffyClean** [comment]
I've just added a bit more stuff, aiming to fix the edge case I pointed out at the start of the pull request. By doing it, I ended up clearing another edge case.

**Pull request merged**
