### PR TITLE
Initial accessibility related changes

### PR DESCRIPTION
**Pull request by rpkoller**
An initial batch of changes. Still a lot to do. Please take a look first and test and also fix and adjust possible problems you notice. Mentioned here there are still a few fields left to cover: https://github.com/aatishb/covidtrends/issues/123#issuecomment-619262959

### CODE REVIEW

**Comment by rpkoller** [comment]
Aside the color contrast please check the micro copy in `aria-label` and `labels`

**Comment by rpkoller** [comment]
Got a first feedback in the a11y slack channel. in regards of the gradient. as usual it depends. but if the range of the two background colors is narrow and the text maintains sufficient contrast and the color values arent too bright it should be ok for the moment. we should leave it as is for the moment. the the only thing to check in regards of color contrast are the three buttons.

and the markup i have to research a little further cuz in contrast to as i initially thought `aside`isnt appropriate. it is only allowed for additional related information like where data is from or other sources not for view control purposes.

**Comment by aatishb** [comment]
@rpkoller This looks great. Just working on the color contrast. ok with you if I commit some edits to this PR? We can discuss before merging.

For the search I felt the label was a bit redundant as we can use the search text to indicate its purpose, and so I did this and added aria-label to it.

**Comment by rpkoller** [comment]
totally fine with me if you extend the PR with more commits... and yep we can discuss before merging. the only thing i am uncertain i am able to is push more changes on my side up. cuz i got your commit downloaded to my local copy but now not allowed to push the changes to my origin. ;)

and yep saw your change removing the regular label from search. but since you've added the aria-label to the field it should be fine. in that case. the label made it a bit confusing alongside the line notes before in regards auf the 50 case minimum.

**Comment by aatishb** [comment]
Hi @rpkoller all looks great on my end, thanks for all your work on this. I think we can merge this. Made a few commits above, let me know if you have any changes to suggest.

**Comment by rpkoller** [comment]
hmm i have only two comments. first is a question about your last commit:

```
placeholder="Search For A Location" aria-label="Search For A Region"
```
why call it in the placeholder a location and in the label a region? not sure if it would be better to be consistent. 

and about the button colors. the standard is now a little darker. 

Bildschirmfoto 2020-04-26 um 23 56 06
and on hover the old color

Bildschirmfoto 2020-04-26 um 23 56 12

the darker color combination looks a bit odd in conjunction with the heading color in the old brighter red. and on hover the color of the button gets in line with the heading color. unsure if maybe another color for the button in general might be th better choice?

**Comment by rpkoller** [comment]
@aatishb on first sight it looks a bit unusual  (my brain got way too used to the red buttons) but i see what you did there. ;) the new colors look like the ones identical to the gradient or at least pretty much similar. excellent idea! and the contrast is also way better with the new combinations than before. very good idea!

**Comment by aatishb** [comment]
Yeah I'm just trying to use existing colors on the page for the color scheme. Will go ahead and merge this, and we can always tweak the colors later if needed.

**Pull request merged**
