### PR TITLE
Option to hide marker-labels

### LINKED ISSUE #102: option to hide labels
Try showing the graph with all the countries or US states (e.g. to see how all the dots correlate)..
It's just black, mostly....
Would be great to optionally hide the labels e.g. on the left with the select-options.

wdyt?

### PR DESCRIPTION
**Pull request by thisIsTheFoxe**
Closes #102  

Adds 2 buttons (like the the two de-/select buttons) for hiding and showing the labels. Especially useful when having more many curves in the same place...
The Text-info on hover still works obv...

### CODE REVIEW

**Comment by aatishb** [comment]
Hi @thisIsTheFoxe, if you already have this running on a branch, could you share a link to a live version? No worries if it's inconvenient or you don't already have it up.

**Comment by thisIsTheFoxe** [comment]
Hey, good point @aatishb.. [here you go](https://www.thisisthefoxe.me/covidtrends/)

_I actually had no idea that GH pages work like that.. pretty cool, actually.. thx for (indirectly) letting me know ^^_

**Comment by waldyrious** [comment]
IMO instead of two buttons, which take up a lot of space, it would be more appropriate to make this a checkbox, since it's a simple on/off toggle. I also think it should be in the "Customize" section of the sidebar, rather than the "Countries" section.

| This PR | My proposal |
| - | - |
| Screenshot 2020-04-21 at 18 14 37 | Screenshot 2020-04-21 at 18 14 24 |

**Comment by thisIsTheFoxe** [comment]
@waldyrious that’s what I thought..
But then it matched quite nicely with the selection thing.. but u right.... gonna fix that..

**Comment by waldyrious** [comment]
> - [ ] Hide country labels

Please don't make it a double negative 😄 The checkbox status should match the visibility of the labels: checked = visible, unchecked = invisible. Otherwise it makes things confusing from a UX perspective.

Also I'd suggest using simply "Show labels" instead of "Show country labels", since for the regional plots the "country" designation will be incorrect.

**Comment by aatishb** [comment]
Thanks all for your work on this, it looks great! Am planning to merge this feature.

**Pull request merged**
